// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cubie/BaseCommands.proto

package netcontrol;

public final class Commands {
  private Commands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseCommandsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netcontrol.BaseCommands)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
     */
    netcontrol.Commands.BaseCommands.Type getType();

    /**
     * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
     */
    boolean hasDeviceState();
    /**
     * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
     */
    netcontrol.Commands.DeviceState getDeviceState();
    /**
     * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
     */
    netcontrol.Commands.DeviceStateOrBuilder getDeviceStateOrBuilder();
  }
  /**
   * Protobuf type {@code netcontrol.BaseCommands}
   */
  public static final class BaseCommands extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:netcontrol.BaseCommands)
      BaseCommandsOrBuilder {
    // Use BaseCommands.newBuilder() to construct.
    private BaseCommands(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseCommands(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseCommands defaultInstance;
    public static BaseCommands getDefaultInstance() {
      return defaultInstance;
    }

    public BaseCommands getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseCommands(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              netcontrol.Commands.BaseCommands.Type value = netcontrol.Commands.BaseCommands.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              netcontrol.Commands.DeviceState.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = deviceState_.toBuilder();
              }
              deviceState_ = input.readMessage(netcontrol.Commands.DeviceState.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(deviceState_);
                deviceState_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netcontrol.Commands.internal_static_netcontrol_BaseCommands_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netcontrol.Commands.internal_static_netcontrol_BaseCommands_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              netcontrol.Commands.BaseCommands.class, netcontrol.Commands.BaseCommands.Builder.class);
    }

    public static com.google.protobuf.Parser<BaseCommands> PARSER =
        new com.google.protobuf.AbstractParser<BaseCommands>() {
      public BaseCommands parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseCommands(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BaseCommands> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code netcontrol.BaseCommands.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DEVICE_STATE = 1;</code>
       */
      DEVICE_STATE(0, 1),
      ;

      /**
       * <code>DEVICE_STATE = 1;</code>
       */
      public static final int DEVICE_STATE_VALUE = 1;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return DEVICE_STATE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return netcontrol.Commands.BaseCommands.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:netcontrol.BaseCommands.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private netcontrol.Commands.BaseCommands.Type type_;
    /**
     * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
     */
    public netcontrol.Commands.BaseCommands.Type getType() {
      return type_;
    }

    public static final int DEVICESTATE_FIELD_NUMBER = 2;
    private netcontrol.Commands.DeviceState deviceState_;
    /**
     * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
     */
    public boolean hasDeviceState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
     */
    public netcontrol.Commands.DeviceState getDeviceState() {
      return deviceState_;
    }
    /**
     * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
     */
    public netcontrol.Commands.DeviceStateOrBuilder getDeviceStateOrBuilder() {
      return deviceState_;
    }

    private void initFields() {
      type_ = netcontrol.Commands.BaseCommands.Type.DEVICE_STATE;
      deviceState_ = netcontrol.Commands.DeviceState.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasDeviceState()) {
        if (!getDeviceState().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, deviceState_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, deviceState_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static netcontrol.Commands.BaseCommands parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netcontrol.Commands.BaseCommands parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netcontrol.Commands.BaseCommands parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netcontrol.Commands.BaseCommands parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netcontrol.Commands.BaseCommands parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static netcontrol.Commands.BaseCommands parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static netcontrol.Commands.BaseCommands parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static netcontrol.Commands.BaseCommands parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static netcontrol.Commands.BaseCommands parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static netcontrol.Commands.BaseCommands parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(netcontrol.Commands.BaseCommands prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netcontrol.BaseCommands}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netcontrol.BaseCommands)
        netcontrol.Commands.BaseCommandsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return netcontrol.Commands.internal_static_netcontrol_BaseCommands_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return netcontrol.Commands.internal_static_netcontrol_BaseCommands_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                netcontrol.Commands.BaseCommands.class, netcontrol.Commands.BaseCommands.Builder.class);
      }

      // Construct using netcontrol.Commands.BaseCommands.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDeviceStateFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = netcontrol.Commands.BaseCommands.Type.DEVICE_STATE;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (deviceStateBuilder_ == null) {
          deviceState_ = netcontrol.Commands.DeviceState.getDefaultInstance();
        } else {
          deviceStateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return netcontrol.Commands.internal_static_netcontrol_BaseCommands_descriptor;
      }

      public netcontrol.Commands.BaseCommands getDefaultInstanceForType() {
        return netcontrol.Commands.BaseCommands.getDefaultInstance();
      }

      public netcontrol.Commands.BaseCommands build() {
        netcontrol.Commands.BaseCommands result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public netcontrol.Commands.BaseCommands buildPartial() {
        netcontrol.Commands.BaseCommands result = new netcontrol.Commands.BaseCommands(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (deviceStateBuilder_ == null) {
          result.deviceState_ = deviceState_;
        } else {
          result.deviceState_ = deviceStateBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof netcontrol.Commands.BaseCommands) {
          return mergeFrom((netcontrol.Commands.BaseCommands)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(netcontrol.Commands.BaseCommands other) {
        if (other == netcontrol.Commands.BaseCommands.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasDeviceState()) {
          mergeDeviceState(other.getDeviceState());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasDeviceState()) {
          if (!getDeviceState().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        netcontrol.Commands.BaseCommands parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (netcontrol.Commands.BaseCommands) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private netcontrol.Commands.BaseCommands.Type type_ = netcontrol.Commands.BaseCommands.Type.DEVICE_STATE;
      /**
       * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
       */
      public netcontrol.Commands.BaseCommands.Type getType() {
        return type_;
      }
      /**
       * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
       */
      public Builder setType(netcontrol.Commands.BaseCommands.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = netcontrol.Commands.BaseCommands.Type.DEVICE_STATE;
        onChanged();
        return this;
      }

      private netcontrol.Commands.DeviceState deviceState_ = netcontrol.Commands.DeviceState.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          netcontrol.Commands.DeviceState, netcontrol.Commands.DeviceState.Builder, netcontrol.Commands.DeviceStateOrBuilder> deviceStateBuilder_;
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public boolean hasDeviceState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public netcontrol.Commands.DeviceState getDeviceState() {
        if (deviceStateBuilder_ == null) {
          return deviceState_;
        } else {
          return deviceStateBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public Builder setDeviceState(netcontrol.Commands.DeviceState value) {
        if (deviceStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deviceState_ = value;
          onChanged();
        } else {
          deviceStateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public Builder setDeviceState(
          netcontrol.Commands.DeviceState.Builder builderForValue) {
        if (deviceStateBuilder_ == null) {
          deviceState_ = builderForValue.build();
          onChanged();
        } else {
          deviceStateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public Builder mergeDeviceState(netcontrol.Commands.DeviceState value) {
        if (deviceStateBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              deviceState_ != netcontrol.Commands.DeviceState.getDefaultInstance()) {
            deviceState_ =
              netcontrol.Commands.DeviceState.newBuilder(deviceState_).mergeFrom(value).buildPartial();
          } else {
            deviceState_ = value;
          }
          onChanged();
        } else {
          deviceStateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public Builder clearDeviceState() {
        if (deviceStateBuilder_ == null) {
          deviceState_ = netcontrol.Commands.DeviceState.getDefaultInstance();
          onChanged();
        } else {
          deviceStateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public netcontrol.Commands.DeviceState.Builder getDeviceStateBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDeviceStateFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public netcontrol.Commands.DeviceStateOrBuilder getDeviceStateOrBuilder() {
        if (deviceStateBuilder_ != null) {
          return deviceStateBuilder_.getMessageOrBuilder();
        } else {
          return deviceState_;
        }
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          netcontrol.Commands.DeviceState, netcontrol.Commands.DeviceState.Builder, netcontrol.Commands.DeviceStateOrBuilder> 
          getDeviceStateFieldBuilder() {
        if (deviceStateBuilder_ == null) {
          deviceStateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              netcontrol.Commands.DeviceState, netcontrol.Commands.DeviceState.Builder, netcontrol.Commands.DeviceStateOrBuilder>(
                  getDeviceState(),
                  getParentForChildren(),
                  isClean());
          deviceState_ = null;
        }
        return deviceStateBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:netcontrol.BaseCommands)
    }

    static {
      defaultInstance = new BaseCommands(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netcontrol.BaseCommands)
  }

  public interface DeviceStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netcontrol.DeviceState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
     */
    netcontrol.Commands.DeviceState.Direction getType();

    /**
     * <code>optional float sound = 2;</code>
     */
    boolean hasSound();
    /**
     * <code>optional float sound = 2;</code>
     */
    float getSound();

    /**
     * <code>optional bool power = 3 [default = true];</code>
     */
    boolean hasPower();
    /**
     * <code>optional bool power = 3 [default = true];</code>
     */
    boolean getPower();
  }
  /**
   * Protobuf type {@code netcontrol.DeviceState}
   */
  public static final class DeviceState extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:netcontrol.DeviceState)
      DeviceStateOrBuilder {
    // Use DeviceState.newBuilder() to construct.
    private DeviceState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeviceState(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeviceState defaultInstance;
    public static DeviceState getDefaultInstance() {
      return defaultInstance;
    }

    public DeviceState getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              netcontrol.Commands.DeviceState.Direction value = netcontrol.Commands.DeviceState.Direction.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              sound_ = input.readFloat();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              power_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netcontrol.Commands.internal_static_netcontrol_DeviceState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netcontrol.Commands.internal_static_netcontrol_DeviceState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              netcontrol.Commands.DeviceState.class, netcontrol.Commands.DeviceState.Builder.class);
    }

    public static com.google.protobuf.Parser<DeviceState> PARSER =
        new com.google.protobuf.AbstractParser<DeviceState>() {
      public DeviceState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceState(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceState> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code netcontrol.DeviceState.Direction}
     */
    public enum Direction
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>READ = 1;</code>
       */
      READ(0, 1),
      /**
       * <code>WRITE = 2;</code>
       */
      WRITE(1, 2),
      ;

      /**
       * <code>READ = 1;</code>
       */
      public static final int READ_VALUE = 1;
      /**
       * <code>WRITE = 2;</code>
       */
      public static final int WRITE_VALUE = 2;


      public final int getNumber() { return value; }

      public static Direction valueOf(int value) {
        switch (value) {
          case 1: return READ;
          case 2: return WRITE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Direction>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Direction>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Direction>() {
              public Direction findValueByNumber(int number) {
                return Direction.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return netcontrol.Commands.DeviceState.getDescriptor().getEnumTypes().get(0);
      }

      private static final Direction[] VALUES = values();

      public static Direction valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Direction(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:netcontrol.DeviceState.Direction)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private netcontrol.Commands.DeviceState.Direction type_;
    /**
     * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
     */
    public netcontrol.Commands.DeviceState.Direction getType() {
      return type_;
    }

    public static final int SOUND_FIELD_NUMBER = 2;
    private float sound_;
    /**
     * <code>optional float sound = 2;</code>
     */
    public boolean hasSound() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional float sound = 2;</code>
     */
    public float getSound() {
      return sound_;
    }

    public static final int POWER_FIELD_NUMBER = 3;
    private boolean power_;
    /**
     * <code>optional bool power = 3 [default = true];</code>
     */
    public boolean hasPower() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool power = 3 [default = true];</code>
     */
    public boolean getPower() {
      return power_;
    }

    private void initFields() {
      type_ = netcontrol.Commands.DeviceState.Direction.READ;
      sound_ = 0F;
      power_ = true;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, sound_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, power_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, sound_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, power_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static netcontrol.Commands.DeviceState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netcontrol.Commands.DeviceState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netcontrol.Commands.DeviceState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netcontrol.Commands.DeviceState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netcontrol.Commands.DeviceState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static netcontrol.Commands.DeviceState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static netcontrol.Commands.DeviceState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static netcontrol.Commands.DeviceState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static netcontrol.Commands.DeviceState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static netcontrol.Commands.DeviceState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(netcontrol.Commands.DeviceState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netcontrol.DeviceState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netcontrol.DeviceState)
        netcontrol.Commands.DeviceStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return netcontrol.Commands.internal_static_netcontrol_DeviceState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return netcontrol.Commands.internal_static_netcontrol_DeviceState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                netcontrol.Commands.DeviceState.class, netcontrol.Commands.DeviceState.Builder.class);
      }

      // Construct using netcontrol.Commands.DeviceState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = netcontrol.Commands.DeviceState.Direction.READ;
        bitField0_ = (bitField0_ & ~0x00000001);
        sound_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        power_ = true;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return netcontrol.Commands.internal_static_netcontrol_DeviceState_descriptor;
      }

      public netcontrol.Commands.DeviceState getDefaultInstanceForType() {
        return netcontrol.Commands.DeviceState.getDefaultInstance();
      }

      public netcontrol.Commands.DeviceState build() {
        netcontrol.Commands.DeviceState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public netcontrol.Commands.DeviceState buildPartial() {
        netcontrol.Commands.DeviceState result = new netcontrol.Commands.DeviceState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sound_ = sound_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.power_ = power_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof netcontrol.Commands.DeviceState) {
          return mergeFrom((netcontrol.Commands.DeviceState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(netcontrol.Commands.DeviceState other) {
        if (other == netcontrol.Commands.DeviceState.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSound()) {
          setSound(other.getSound());
        }
        if (other.hasPower()) {
          setPower(other.getPower());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        netcontrol.Commands.DeviceState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (netcontrol.Commands.DeviceState) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private netcontrol.Commands.DeviceState.Direction type_ = netcontrol.Commands.DeviceState.Direction.READ;
      /**
       * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
       */
      public netcontrol.Commands.DeviceState.Direction getType() {
        return type_;
      }
      /**
       * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
       */
      public Builder setType(netcontrol.Commands.DeviceState.Direction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = netcontrol.Commands.DeviceState.Direction.READ;
        onChanged();
        return this;
      }

      private float sound_ ;
      /**
       * <code>optional float sound = 2;</code>
       */
      public boolean hasSound() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional float sound = 2;</code>
       */
      public float getSound() {
        return sound_;
      }
      /**
       * <code>optional float sound = 2;</code>
       */
      public Builder setSound(float value) {
        bitField0_ |= 0x00000002;
        sound_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float sound = 2;</code>
       */
      public Builder clearSound() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sound_ = 0F;
        onChanged();
        return this;
      }

      private boolean power_ = true;
      /**
       * <code>optional bool power = 3 [default = true];</code>
       */
      public boolean hasPower() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool power = 3 [default = true];</code>
       */
      public boolean getPower() {
        return power_;
      }
      /**
       * <code>optional bool power = 3 [default = true];</code>
       */
      public Builder setPower(boolean value) {
        bitField0_ |= 0x00000004;
        power_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool power = 3 [default = true];</code>
       */
      public Builder clearPower() {
        bitField0_ = (bitField0_ & ~0x00000004);
        power_ = true;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netcontrol.DeviceState)
    }

    static {
      defaultInstance = new DeviceState(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netcontrol.DeviceState)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netcontrol_BaseCommands_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netcontrol_BaseCommands_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netcontrol_DeviceState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netcontrol_DeviceState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030Cubie/BaseCommands.proto\022\nnetcontrol\"\203" +
      "\001\n\014BaseCommands\022+\n\004type\030\001 \002(\0162\035.netcontr" +
      "ol.BaseCommands.Type\022,\n\013deviceState\030\002 \001(" +
      "\0132\027.netcontrol.DeviceState\"\030\n\004Type\022\020\n\014DE" +
      "VICE_STATE\020\001\"\204\001\n\013DeviceState\022/\n\004type\030\001 \002" +
      "(\0162!.netcontrol.DeviceState.Direction\022\r\n" +
      "\005sound\030\002 \001(\002\022\023\n\005power\030\003 \001(\010:\004true\" \n\tDir" +
      "ection\022\010\n\004READ\020\001\022\t\n\005WRITE\020\002B\nB\010Commands"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netcontrol_BaseCommands_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netcontrol_BaseCommands_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_netcontrol_BaseCommands_descriptor,
        new java.lang.String[] { "Type", "DeviceState", });
    internal_static_netcontrol_DeviceState_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_netcontrol_DeviceState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_netcontrol_DeviceState_descriptor,
        new java.lang.String[] { "Type", "Sound", "Power", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
