// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cubie/BaseCommands.proto

package netcontrol;

public final class Commands {
  private Commands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseCommandsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netcontrol.BaseCommands)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
     */
    netcontrol.Commands.BaseCommands.Type getType();

    /**
     * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
     */
    boolean hasDeviceState();
    /**
     * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
     */
    netcontrol.Commands.DeviceState getDeviceState();
    /**
     * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
     */
    netcontrol.Commands.DeviceStateOrBuilder getDeviceStateOrBuilder();

    /**
     * <code>optional .netcontrol.StreamSound streamSound = 3;</code>
     */
    boolean hasStreamSound();
    /**
     * <code>optional .netcontrol.StreamSound streamSound = 3;</code>
     */
    netcontrol.Commands.StreamSound getStreamSound();
    /**
     * <code>optional .netcontrol.StreamSound streamSound = 3;</code>
     */
    netcontrol.Commands.StreamSoundOrBuilder getStreamSoundOrBuilder();

    /**
     * <code>optional .netcontrol.FairyTale fairyTale = 4;</code>
     */
    boolean hasFairyTale();
    /**
     * <code>optional .netcontrol.FairyTale fairyTale = 4;</code>
     */
    netcontrol.Commands.FairyTale getFairyTale();
    /**
     * <code>optional .netcontrol.FairyTale fairyTale = 4;</code>
     */
    netcontrol.Commands.FairyTaleOrBuilder getFairyTaleOrBuilder();
  }
  /**
   * Protobuf type {@code netcontrol.BaseCommands}
   */
  public static final class BaseCommands extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:netcontrol.BaseCommands)
      BaseCommandsOrBuilder {
    // Use BaseCommands.newBuilder() to construct.
    private BaseCommands(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseCommands(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseCommands defaultInstance;
    public static BaseCommands getDefaultInstance() {
      return defaultInstance;
    }

    public BaseCommands getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseCommands(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              netcontrol.Commands.BaseCommands.Type value = netcontrol.Commands.BaseCommands.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              netcontrol.Commands.DeviceState.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = deviceState_.toBuilder();
              }
              deviceState_ = input.readMessage(netcontrol.Commands.DeviceState.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(deviceState_);
                deviceState_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              netcontrol.Commands.StreamSound.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = streamSound_.toBuilder();
              }
              streamSound_ = input.readMessage(netcontrol.Commands.StreamSound.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(streamSound_);
                streamSound_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              netcontrol.Commands.FairyTale.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = fairyTale_.toBuilder();
              }
              fairyTale_ = input.readMessage(netcontrol.Commands.FairyTale.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fairyTale_);
                fairyTale_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netcontrol.Commands.internal_static_netcontrol_BaseCommands_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netcontrol.Commands.internal_static_netcontrol_BaseCommands_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              netcontrol.Commands.BaseCommands.class, netcontrol.Commands.BaseCommands.Builder.class);
    }

    public static com.google.protobuf.Parser<BaseCommands> PARSER =
        new com.google.protobuf.AbstractParser<BaseCommands>() {
      public BaseCommands parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseCommands(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BaseCommands> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code netcontrol.BaseCommands.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DEVICE_STATE = 1;</code>
       */
      DEVICE_STATE(0, 1),
      /**
       * <code>STREAM_SOUND = 2;</code>
       */
      STREAM_SOUND(1, 2),
      /**
       * <code>FAIRY_TALE = 3;</code>
       */
      FAIRY_TALE(2, 3),
      ;

      /**
       * <code>DEVICE_STATE = 1;</code>
       */
      public static final int DEVICE_STATE_VALUE = 1;
      /**
       * <code>STREAM_SOUND = 2;</code>
       */
      public static final int STREAM_SOUND_VALUE = 2;
      /**
       * <code>FAIRY_TALE = 3;</code>
       */
      public static final int FAIRY_TALE_VALUE = 3;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return DEVICE_STATE;
          case 2: return STREAM_SOUND;
          case 3: return FAIRY_TALE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return netcontrol.Commands.BaseCommands.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:netcontrol.BaseCommands.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private netcontrol.Commands.BaseCommands.Type type_;
    /**
     * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
     */
    public netcontrol.Commands.BaseCommands.Type getType() {
      return type_;
    }

    public static final int DEVICESTATE_FIELD_NUMBER = 2;
    private netcontrol.Commands.DeviceState deviceState_;
    /**
     * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
     */
    public boolean hasDeviceState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
     */
    public netcontrol.Commands.DeviceState getDeviceState() {
      return deviceState_;
    }
    /**
     * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
     */
    public netcontrol.Commands.DeviceStateOrBuilder getDeviceStateOrBuilder() {
      return deviceState_;
    }

    public static final int STREAMSOUND_FIELD_NUMBER = 3;
    private netcontrol.Commands.StreamSound streamSound_;
    /**
     * <code>optional .netcontrol.StreamSound streamSound = 3;</code>
     */
    public boolean hasStreamSound() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .netcontrol.StreamSound streamSound = 3;</code>
     */
    public netcontrol.Commands.StreamSound getStreamSound() {
      return streamSound_;
    }
    /**
     * <code>optional .netcontrol.StreamSound streamSound = 3;</code>
     */
    public netcontrol.Commands.StreamSoundOrBuilder getStreamSoundOrBuilder() {
      return streamSound_;
    }

    public static final int FAIRYTALE_FIELD_NUMBER = 4;
    private netcontrol.Commands.FairyTale fairyTale_;
    /**
     * <code>optional .netcontrol.FairyTale fairyTale = 4;</code>
     */
    public boolean hasFairyTale() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .netcontrol.FairyTale fairyTale = 4;</code>
     */
    public netcontrol.Commands.FairyTale getFairyTale() {
      return fairyTale_;
    }
    /**
     * <code>optional .netcontrol.FairyTale fairyTale = 4;</code>
     */
    public netcontrol.Commands.FairyTaleOrBuilder getFairyTaleOrBuilder() {
      return fairyTale_;
    }

    private void initFields() {
      type_ = netcontrol.Commands.BaseCommands.Type.DEVICE_STATE;
      deviceState_ = netcontrol.Commands.DeviceState.getDefaultInstance();
      streamSound_ = netcontrol.Commands.StreamSound.getDefaultInstance();
      fairyTale_ = netcontrol.Commands.FairyTale.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasDeviceState()) {
        if (!getDeviceState().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasStreamSound()) {
        if (!getStreamSound().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasFairyTale()) {
        if (!getFairyTale().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, deviceState_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, streamSound_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, fairyTale_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, deviceState_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, streamSound_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, fairyTale_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static netcontrol.Commands.BaseCommands parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netcontrol.Commands.BaseCommands parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netcontrol.Commands.BaseCommands parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netcontrol.Commands.BaseCommands parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netcontrol.Commands.BaseCommands parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static netcontrol.Commands.BaseCommands parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static netcontrol.Commands.BaseCommands parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static netcontrol.Commands.BaseCommands parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static netcontrol.Commands.BaseCommands parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static netcontrol.Commands.BaseCommands parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(netcontrol.Commands.BaseCommands prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netcontrol.BaseCommands}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netcontrol.BaseCommands)
        netcontrol.Commands.BaseCommandsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return netcontrol.Commands.internal_static_netcontrol_BaseCommands_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return netcontrol.Commands.internal_static_netcontrol_BaseCommands_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                netcontrol.Commands.BaseCommands.class, netcontrol.Commands.BaseCommands.Builder.class);
      }

      // Construct using netcontrol.Commands.BaseCommands.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDeviceStateFieldBuilder();
          getStreamSoundFieldBuilder();
          getFairyTaleFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = netcontrol.Commands.BaseCommands.Type.DEVICE_STATE;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (deviceStateBuilder_ == null) {
          deviceState_ = netcontrol.Commands.DeviceState.getDefaultInstance();
        } else {
          deviceStateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (streamSoundBuilder_ == null) {
          streamSound_ = netcontrol.Commands.StreamSound.getDefaultInstance();
        } else {
          streamSoundBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (fairyTaleBuilder_ == null) {
          fairyTale_ = netcontrol.Commands.FairyTale.getDefaultInstance();
        } else {
          fairyTaleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return netcontrol.Commands.internal_static_netcontrol_BaseCommands_descriptor;
      }

      public netcontrol.Commands.BaseCommands getDefaultInstanceForType() {
        return netcontrol.Commands.BaseCommands.getDefaultInstance();
      }

      public netcontrol.Commands.BaseCommands build() {
        netcontrol.Commands.BaseCommands result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public netcontrol.Commands.BaseCommands buildPartial() {
        netcontrol.Commands.BaseCommands result = new netcontrol.Commands.BaseCommands(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (deviceStateBuilder_ == null) {
          result.deviceState_ = deviceState_;
        } else {
          result.deviceState_ = deviceStateBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (streamSoundBuilder_ == null) {
          result.streamSound_ = streamSound_;
        } else {
          result.streamSound_ = streamSoundBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (fairyTaleBuilder_ == null) {
          result.fairyTale_ = fairyTale_;
        } else {
          result.fairyTale_ = fairyTaleBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof netcontrol.Commands.BaseCommands) {
          return mergeFrom((netcontrol.Commands.BaseCommands)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(netcontrol.Commands.BaseCommands other) {
        if (other == netcontrol.Commands.BaseCommands.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasDeviceState()) {
          mergeDeviceState(other.getDeviceState());
        }
        if (other.hasStreamSound()) {
          mergeStreamSound(other.getStreamSound());
        }
        if (other.hasFairyTale()) {
          mergeFairyTale(other.getFairyTale());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasDeviceState()) {
          if (!getDeviceState().isInitialized()) {
            
            return false;
          }
        }
        if (hasStreamSound()) {
          if (!getStreamSound().isInitialized()) {
            
            return false;
          }
        }
        if (hasFairyTale()) {
          if (!getFairyTale().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        netcontrol.Commands.BaseCommands parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (netcontrol.Commands.BaseCommands) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private netcontrol.Commands.BaseCommands.Type type_ = netcontrol.Commands.BaseCommands.Type.DEVICE_STATE;
      /**
       * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
       */
      public netcontrol.Commands.BaseCommands.Type getType() {
        return type_;
      }
      /**
       * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
       */
      public Builder setType(netcontrol.Commands.BaseCommands.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .netcontrol.BaseCommands.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = netcontrol.Commands.BaseCommands.Type.DEVICE_STATE;
        onChanged();
        return this;
      }

      private netcontrol.Commands.DeviceState deviceState_ = netcontrol.Commands.DeviceState.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          netcontrol.Commands.DeviceState, netcontrol.Commands.DeviceState.Builder, netcontrol.Commands.DeviceStateOrBuilder> deviceStateBuilder_;
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public boolean hasDeviceState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public netcontrol.Commands.DeviceState getDeviceState() {
        if (deviceStateBuilder_ == null) {
          return deviceState_;
        } else {
          return deviceStateBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public Builder setDeviceState(netcontrol.Commands.DeviceState value) {
        if (deviceStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deviceState_ = value;
          onChanged();
        } else {
          deviceStateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public Builder setDeviceState(
          netcontrol.Commands.DeviceState.Builder builderForValue) {
        if (deviceStateBuilder_ == null) {
          deviceState_ = builderForValue.build();
          onChanged();
        } else {
          deviceStateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public Builder mergeDeviceState(netcontrol.Commands.DeviceState value) {
        if (deviceStateBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              deviceState_ != netcontrol.Commands.DeviceState.getDefaultInstance()) {
            deviceState_ =
              netcontrol.Commands.DeviceState.newBuilder(deviceState_).mergeFrom(value).buildPartial();
          } else {
            deviceState_ = value;
          }
          onChanged();
        } else {
          deviceStateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public Builder clearDeviceState() {
        if (deviceStateBuilder_ == null) {
          deviceState_ = netcontrol.Commands.DeviceState.getDefaultInstance();
          onChanged();
        } else {
          deviceStateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public netcontrol.Commands.DeviceState.Builder getDeviceStateBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDeviceStateFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      public netcontrol.Commands.DeviceStateOrBuilder getDeviceStateOrBuilder() {
        if (deviceStateBuilder_ != null) {
          return deviceStateBuilder_.getMessageOrBuilder();
        } else {
          return deviceState_;
        }
      }
      /**
       * <code>optional .netcontrol.DeviceState deviceState = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          netcontrol.Commands.DeviceState, netcontrol.Commands.DeviceState.Builder, netcontrol.Commands.DeviceStateOrBuilder> 
          getDeviceStateFieldBuilder() {
        if (deviceStateBuilder_ == null) {
          deviceStateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              netcontrol.Commands.DeviceState, netcontrol.Commands.DeviceState.Builder, netcontrol.Commands.DeviceStateOrBuilder>(
                  getDeviceState(),
                  getParentForChildren(),
                  isClean());
          deviceState_ = null;
        }
        return deviceStateBuilder_;
      }

      private netcontrol.Commands.StreamSound streamSound_ = netcontrol.Commands.StreamSound.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          netcontrol.Commands.StreamSound, netcontrol.Commands.StreamSound.Builder, netcontrol.Commands.StreamSoundOrBuilder> streamSoundBuilder_;
      /**
       * <code>optional .netcontrol.StreamSound streamSound = 3;</code>
       */
      public boolean hasStreamSound() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .netcontrol.StreamSound streamSound = 3;</code>
       */
      public netcontrol.Commands.StreamSound getStreamSound() {
        if (streamSoundBuilder_ == null) {
          return streamSound_;
        } else {
          return streamSoundBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .netcontrol.StreamSound streamSound = 3;</code>
       */
      public Builder setStreamSound(netcontrol.Commands.StreamSound value) {
        if (streamSoundBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          streamSound_ = value;
          onChanged();
        } else {
          streamSoundBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .netcontrol.StreamSound streamSound = 3;</code>
       */
      public Builder setStreamSound(
          netcontrol.Commands.StreamSound.Builder builderForValue) {
        if (streamSoundBuilder_ == null) {
          streamSound_ = builderForValue.build();
          onChanged();
        } else {
          streamSoundBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .netcontrol.StreamSound streamSound = 3;</code>
       */
      public Builder mergeStreamSound(netcontrol.Commands.StreamSound value) {
        if (streamSoundBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              streamSound_ != netcontrol.Commands.StreamSound.getDefaultInstance()) {
            streamSound_ =
              netcontrol.Commands.StreamSound.newBuilder(streamSound_).mergeFrom(value).buildPartial();
          } else {
            streamSound_ = value;
          }
          onChanged();
        } else {
          streamSoundBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .netcontrol.StreamSound streamSound = 3;</code>
       */
      public Builder clearStreamSound() {
        if (streamSoundBuilder_ == null) {
          streamSound_ = netcontrol.Commands.StreamSound.getDefaultInstance();
          onChanged();
        } else {
          streamSoundBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .netcontrol.StreamSound streamSound = 3;</code>
       */
      public netcontrol.Commands.StreamSound.Builder getStreamSoundBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getStreamSoundFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .netcontrol.StreamSound streamSound = 3;</code>
       */
      public netcontrol.Commands.StreamSoundOrBuilder getStreamSoundOrBuilder() {
        if (streamSoundBuilder_ != null) {
          return streamSoundBuilder_.getMessageOrBuilder();
        } else {
          return streamSound_;
        }
      }
      /**
       * <code>optional .netcontrol.StreamSound streamSound = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          netcontrol.Commands.StreamSound, netcontrol.Commands.StreamSound.Builder, netcontrol.Commands.StreamSoundOrBuilder> 
          getStreamSoundFieldBuilder() {
        if (streamSoundBuilder_ == null) {
          streamSoundBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              netcontrol.Commands.StreamSound, netcontrol.Commands.StreamSound.Builder, netcontrol.Commands.StreamSoundOrBuilder>(
                  getStreamSound(),
                  getParentForChildren(),
                  isClean());
          streamSound_ = null;
        }
        return streamSoundBuilder_;
      }

      private netcontrol.Commands.FairyTale fairyTale_ = netcontrol.Commands.FairyTale.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          netcontrol.Commands.FairyTale, netcontrol.Commands.FairyTale.Builder, netcontrol.Commands.FairyTaleOrBuilder> fairyTaleBuilder_;
      /**
       * <code>optional .netcontrol.FairyTale fairyTale = 4;</code>
       */
      public boolean hasFairyTale() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .netcontrol.FairyTale fairyTale = 4;</code>
       */
      public netcontrol.Commands.FairyTale getFairyTale() {
        if (fairyTaleBuilder_ == null) {
          return fairyTale_;
        } else {
          return fairyTaleBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .netcontrol.FairyTale fairyTale = 4;</code>
       */
      public Builder setFairyTale(netcontrol.Commands.FairyTale value) {
        if (fairyTaleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fairyTale_ = value;
          onChanged();
        } else {
          fairyTaleBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .netcontrol.FairyTale fairyTale = 4;</code>
       */
      public Builder setFairyTale(
          netcontrol.Commands.FairyTale.Builder builderForValue) {
        if (fairyTaleBuilder_ == null) {
          fairyTale_ = builderForValue.build();
          onChanged();
        } else {
          fairyTaleBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .netcontrol.FairyTale fairyTale = 4;</code>
       */
      public Builder mergeFairyTale(netcontrol.Commands.FairyTale value) {
        if (fairyTaleBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              fairyTale_ != netcontrol.Commands.FairyTale.getDefaultInstance()) {
            fairyTale_ =
              netcontrol.Commands.FairyTale.newBuilder(fairyTale_).mergeFrom(value).buildPartial();
          } else {
            fairyTale_ = value;
          }
          onChanged();
        } else {
          fairyTaleBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .netcontrol.FairyTale fairyTale = 4;</code>
       */
      public Builder clearFairyTale() {
        if (fairyTaleBuilder_ == null) {
          fairyTale_ = netcontrol.Commands.FairyTale.getDefaultInstance();
          onChanged();
        } else {
          fairyTaleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .netcontrol.FairyTale fairyTale = 4;</code>
       */
      public netcontrol.Commands.FairyTale.Builder getFairyTaleBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getFairyTaleFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .netcontrol.FairyTale fairyTale = 4;</code>
       */
      public netcontrol.Commands.FairyTaleOrBuilder getFairyTaleOrBuilder() {
        if (fairyTaleBuilder_ != null) {
          return fairyTaleBuilder_.getMessageOrBuilder();
        } else {
          return fairyTale_;
        }
      }
      /**
       * <code>optional .netcontrol.FairyTale fairyTale = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          netcontrol.Commands.FairyTale, netcontrol.Commands.FairyTale.Builder, netcontrol.Commands.FairyTaleOrBuilder> 
          getFairyTaleFieldBuilder() {
        if (fairyTaleBuilder_ == null) {
          fairyTaleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              netcontrol.Commands.FairyTale, netcontrol.Commands.FairyTale.Builder, netcontrol.Commands.FairyTaleOrBuilder>(
                  getFairyTale(),
                  getParentForChildren(),
                  isClean());
          fairyTale_ = null;
        }
        return fairyTaleBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:netcontrol.BaseCommands)
    }

    static {
      defaultInstance = new BaseCommands(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netcontrol.BaseCommands)
  }

  public interface DeviceStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netcontrol.DeviceState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
     */
    netcontrol.Commands.DeviceState.Direction getType();

    /**
     * <code>optional float sound = 2;</code>
     */
    boolean hasSound();
    /**
     * <code>optional float sound = 2;</code>
     */
    float getSound();

    /**
     * <code>optional bool power = 3;</code>
     */
    boolean hasPower();
    /**
     * <code>optional bool power = 3;</code>
     */
    boolean getPower();
  }
  /**
   * Protobuf type {@code netcontrol.DeviceState}
   */
  public static final class DeviceState extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:netcontrol.DeviceState)
      DeviceStateOrBuilder {
    // Use DeviceState.newBuilder() to construct.
    private DeviceState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeviceState(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeviceState defaultInstance;
    public static DeviceState getDefaultInstance() {
      return defaultInstance;
    }

    public DeviceState getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              netcontrol.Commands.DeviceState.Direction value = netcontrol.Commands.DeviceState.Direction.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              sound_ = input.readFloat();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              power_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netcontrol.Commands.internal_static_netcontrol_DeviceState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netcontrol.Commands.internal_static_netcontrol_DeviceState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              netcontrol.Commands.DeviceState.class, netcontrol.Commands.DeviceState.Builder.class);
    }

    public static com.google.protobuf.Parser<DeviceState> PARSER =
        new com.google.protobuf.AbstractParser<DeviceState>() {
      public DeviceState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceState(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceState> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code netcontrol.DeviceState.Direction}
     */
    public enum Direction
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>READ = 1;</code>
       */
      READ(0, 1),
      /**
       * <code>WRITE = 2;</code>
       */
      WRITE(1, 2),
      ;

      /**
       * <code>READ = 1;</code>
       */
      public static final int READ_VALUE = 1;
      /**
       * <code>WRITE = 2;</code>
       */
      public static final int WRITE_VALUE = 2;


      public final int getNumber() { return value; }

      public static Direction valueOf(int value) {
        switch (value) {
          case 1: return READ;
          case 2: return WRITE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Direction>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Direction>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Direction>() {
              public Direction findValueByNumber(int number) {
                return Direction.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return netcontrol.Commands.DeviceState.getDescriptor().getEnumTypes().get(0);
      }

      private static final Direction[] VALUES = values();

      public static Direction valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Direction(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:netcontrol.DeviceState.Direction)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private netcontrol.Commands.DeviceState.Direction type_;
    /**
     * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
     */
    public netcontrol.Commands.DeviceState.Direction getType() {
      return type_;
    }

    public static final int SOUND_FIELD_NUMBER = 2;
    private float sound_;
    /**
     * <code>optional float sound = 2;</code>
     */
    public boolean hasSound() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional float sound = 2;</code>
     */
    public float getSound() {
      return sound_;
    }

    public static final int POWER_FIELD_NUMBER = 3;
    private boolean power_;
    /**
     * <code>optional bool power = 3;</code>
     */
    public boolean hasPower() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool power = 3;</code>
     */
    public boolean getPower() {
      return power_;
    }

    private void initFields() {
      type_ = netcontrol.Commands.DeviceState.Direction.READ;
      sound_ = 0F;
      power_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, sound_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, power_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, sound_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, power_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static netcontrol.Commands.DeviceState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netcontrol.Commands.DeviceState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netcontrol.Commands.DeviceState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netcontrol.Commands.DeviceState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netcontrol.Commands.DeviceState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static netcontrol.Commands.DeviceState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static netcontrol.Commands.DeviceState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static netcontrol.Commands.DeviceState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static netcontrol.Commands.DeviceState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static netcontrol.Commands.DeviceState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(netcontrol.Commands.DeviceState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netcontrol.DeviceState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netcontrol.DeviceState)
        netcontrol.Commands.DeviceStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return netcontrol.Commands.internal_static_netcontrol_DeviceState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return netcontrol.Commands.internal_static_netcontrol_DeviceState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                netcontrol.Commands.DeviceState.class, netcontrol.Commands.DeviceState.Builder.class);
      }

      // Construct using netcontrol.Commands.DeviceState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = netcontrol.Commands.DeviceState.Direction.READ;
        bitField0_ = (bitField0_ & ~0x00000001);
        sound_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        power_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return netcontrol.Commands.internal_static_netcontrol_DeviceState_descriptor;
      }

      public netcontrol.Commands.DeviceState getDefaultInstanceForType() {
        return netcontrol.Commands.DeviceState.getDefaultInstance();
      }

      public netcontrol.Commands.DeviceState build() {
        netcontrol.Commands.DeviceState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public netcontrol.Commands.DeviceState buildPartial() {
        netcontrol.Commands.DeviceState result = new netcontrol.Commands.DeviceState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sound_ = sound_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.power_ = power_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof netcontrol.Commands.DeviceState) {
          return mergeFrom((netcontrol.Commands.DeviceState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(netcontrol.Commands.DeviceState other) {
        if (other == netcontrol.Commands.DeviceState.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSound()) {
          setSound(other.getSound());
        }
        if (other.hasPower()) {
          setPower(other.getPower());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        netcontrol.Commands.DeviceState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (netcontrol.Commands.DeviceState) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private netcontrol.Commands.DeviceState.Direction type_ = netcontrol.Commands.DeviceState.Direction.READ;
      /**
       * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
       */
      public netcontrol.Commands.DeviceState.Direction getType() {
        return type_;
      }
      /**
       * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
       */
      public Builder setType(netcontrol.Commands.DeviceState.Direction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .netcontrol.DeviceState.Direction type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = netcontrol.Commands.DeviceState.Direction.READ;
        onChanged();
        return this;
      }

      private float sound_ ;
      /**
       * <code>optional float sound = 2;</code>
       */
      public boolean hasSound() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional float sound = 2;</code>
       */
      public float getSound() {
        return sound_;
      }
      /**
       * <code>optional float sound = 2;</code>
       */
      public Builder setSound(float value) {
        bitField0_ |= 0x00000002;
        sound_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float sound = 2;</code>
       */
      public Builder clearSound() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sound_ = 0F;
        onChanged();
        return this;
      }

      private boolean power_ ;
      /**
       * <code>optional bool power = 3;</code>
       */
      public boolean hasPower() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool power = 3;</code>
       */
      public boolean getPower() {
        return power_;
      }
      /**
       * <code>optional bool power = 3;</code>
       */
      public Builder setPower(boolean value) {
        bitField0_ |= 0x00000004;
        power_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool power = 3;</code>
       */
      public Builder clearPower() {
        bitField0_ = (bitField0_ & ~0x00000004);
        power_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netcontrol.DeviceState)
    }

    static {
      defaultInstance = new DeviceState(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netcontrol.DeviceState)
  }

  public interface StreamSoundOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netcontrol.StreamSound)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 port = 1;</code>
     */
    boolean hasPort();
    /**
     * <code>optional int32 port = 1;</code>
     */
    int getPort();

    /**
     * <code>required bool reload = 2;</code>
     */
    boolean hasReload();
    /**
     * <code>required bool reload = 2;</code>
     */
    boolean getReload();
  }
  /**
   * Protobuf type {@code netcontrol.StreamSound}
   */
  public static final class StreamSound extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:netcontrol.StreamSound)
      StreamSoundOrBuilder {
    // Use StreamSound.newBuilder() to construct.
    private StreamSound(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StreamSound(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StreamSound defaultInstance;
    public static StreamSound getDefaultInstance() {
      return defaultInstance;
    }

    public StreamSound getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StreamSound(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              port_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              reload_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netcontrol.Commands.internal_static_netcontrol_StreamSound_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netcontrol.Commands.internal_static_netcontrol_StreamSound_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              netcontrol.Commands.StreamSound.class, netcontrol.Commands.StreamSound.Builder.class);
    }

    public static com.google.protobuf.Parser<StreamSound> PARSER =
        new com.google.protobuf.AbstractParser<StreamSound>() {
      public StreamSound parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StreamSound(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StreamSound> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PORT_FIELD_NUMBER = 1;
    private int port_;
    /**
     * <code>optional int32 port = 1;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 port = 1;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int RELOAD_FIELD_NUMBER = 2;
    private boolean reload_;
    /**
     * <code>required bool reload = 2;</code>
     */
    public boolean hasReload() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool reload = 2;</code>
     */
    public boolean getReload() {
      return reload_;
    }

    private void initFields() {
      port_ = 0;
      reload_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasReload()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, port_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, reload_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, port_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, reload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static netcontrol.Commands.StreamSound parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netcontrol.Commands.StreamSound parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netcontrol.Commands.StreamSound parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netcontrol.Commands.StreamSound parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netcontrol.Commands.StreamSound parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static netcontrol.Commands.StreamSound parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static netcontrol.Commands.StreamSound parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static netcontrol.Commands.StreamSound parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static netcontrol.Commands.StreamSound parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static netcontrol.Commands.StreamSound parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(netcontrol.Commands.StreamSound prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netcontrol.StreamSound}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netcontrol.StreamSound)
        netcontrol.Commands.StreamSoundOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return netcontrol.Commands.internal_static_netcontrol_StreamSound_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return netcontrol.Commands.internal_static_netcontrol_StreamSound_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                netcontrol.Commands.StreamSound.class, netcontrol.Commands.StreamSound.Builder.class);
      }

      // Construct using netcontrol.Commands.StreamSound.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        reload_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return netcontrol.Commands.internal_static_netcontrol_StreamSound_descriptor;
      }

      public netcontrol.Commands.StreamSound getDefaultInstanceForType() {
        return netcontrol.Commands.StreamSound.getDefaultInstance();
      }

      public netcontrol.Commands.StreamSound build() {
        netcontrol.Commands.StreamSound result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public netcontrol.Commands.StreamSound buildPartial() {
        netcontrol.Commands.StreamSound result = new netcontrol.Commands.StreamSound(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reload_ = reload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof netcontrol.Commands.StreamSound) {
          return mergeFrom((netcontrol.Commands.StreamSound)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(netcontrol.Commands.StreamSound other) {
        if (other == netcontrol.Commands.StreamSound.getDefaultInstance()) return this;
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasReload()) {
          setReload(other.getReload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReload()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        netcontrol.Commands.StreamSound parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (netcontrol.Commands.StreamSound) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int port_ ;
      /**
       * <code>optional int32 port = 1;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 port = 1;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>optional int32 port = 1;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000001;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 port = 1;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        onChanged();
        return this;
      }

      private boolean reload_ ;
      /**
       * <code>required bool reload = 2;</code>
       */
      public boolean hasReload() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool reload = 2;</code>
       */
      public boolean getReload() {
        return reload_;
      }
      /**
       * <code>required bool reload = 2;</code>
       */
      public Builder setReload(boolean value) {
        bitField0_ |= 0x00000002;
        reload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool reload = 2;</code>
       */
      public Builder clearReload() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reload_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netcontrol.StreamSound)
    }

    static {
      defaultInstance = new StreamSound(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netcontrol.StreamSound)
  }

  public interface FairyTaleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netcontrol.FairyTale)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 position = 2 [default = 0];</code>
     */
    boolean hasPosition();
    /**
     * <code>optional int32 position = 2 [default = 0];</code>
     */
    int getPosition();
  }
  /**
   * Protobuf type {@code netcontrol.FairyTale}
   */
  public static final class FairyTale extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:netcontrol.FairyTale)
      FairyTaleOrBuilder {
    // Use FairyTale.newBuilder() to construct.
    private FairyTale(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FairyTale(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FairyTale defaultInstance;
    public static FairyTale getDefaultInstance() {
      return defaultInstance;
    }

    public FairyTale getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FairyTale(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              position_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netcontrol.Commands.internal_static_netcontrol_FairyTale_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netcontrol.Commands.internal_static_netcontrol_FairyTale_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              netcontrol.Commands.FairyTale.class, netcontrol.Commands.FairyTale.Builder.class);
    }

    public static com.google.protobuf.Parser<FairyTale> PARSER =
        new com.google.protobuf.AbstractParser<FairyTale>() {
      public FairyTale parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FairyTale(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FairyTale> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSITION_FIELD_NUMBER = 2;
    private int position_;
    /**
     * <code>optional int32 position = 2 [default = 0];</code>
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 position = 2 [default = 0];</code>
     */
    public int getPosition() {
      return position_;
    }

    private void initFields() {
      name_ = "";
      position_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, position_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, position_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static netcontrol.Commands.FairyTale parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netcontrol.Commands.FairyTale parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netcontrol.Commands.FairyTale parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netcontrol.Commands.FairyTale parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netcontrol.Commands.FairyTale parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static netcontrol.Commands.FairyTale parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static netcontrol.Commands.FairyTale parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static netcontrol.Commands.FairyTale parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static netcontrol.Commands.FairyTale parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static netcontrol.Commands.FairyTale parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(netcontrol.Commands.FairyTale prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netcontrol.FairyTale}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netcontrol.FairyTale)
        netcontrol.Commands.FairyTaleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return netcontrol.Commands.internal_static_netcontrol_FairyTale_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return netcontrol.Commands.internal_static_netcontrol_FairyTale_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                netcontrol.Commands.FairyTale.class, netcontrol.Commands.FairyTale.Builder.class);
      }

      // Construct using netcontrol.Commands.FairyTale.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        position_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return netcontrol.Commands.internal_static_netcontrol_FairyTale_descriptor;
      }

      public netcontrol.Commands.FairyTale getDefaultInstanceForType() {
        return netcontrol.Commands.FairyTale.getDefaultInstance();
      }

      public netcontrol.Commands.FairyTale build() {
        netcontrol.Commands.FairyTale result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public netcontrol.Commands.FairyTale buildPartial() {
        netcontrol.Commands.FairyTale result = new netcontrol.Commands.FairyTale(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.position_ = position_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof netcontrol.Commands.FairyTale) {
          return mergeFrom((netcontrol.Commands.FairyTale)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(netcontrol.Commands.FairyTale other) {
        if (other == netcontrol.Commands.FairyTale.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasPosition()) {
          setPosition(other.getPosition());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        netcontrol.Commands.FairyTale parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (netcontrol.Commands.FairyTale) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int position_ ;
      /**
       * <code>optional int32 position = 2 [default = 0];</code>
       */
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 position = 2 [default = 0];</code>
       */
      public int getPosition() {
        return position_;
      }
      /**
       * <code>optional int32 position = 2 [default = 0];</code>
       */
      public Builder setPosition(int value) {
        bitField0_ |= 0x00000002;
        position_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 position = 2 [default = 0];</code>
       */
      public Builder clearPosition() {
        bitField0_ = (bitField0_ & ~0x00000002);
        position_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netcontrol.FairyTale)
    }

    static {
      defaultInstance = new FairyTale(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netcontrol.FairyTale)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netcontrol_BaseCommands_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netcontrol_BaseCommands_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netcontrol_DeviceState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netcontrol_DeviceState_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netcontrol_StreamSound_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netcontrol_StreamSound_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netcontrol_FairyTale_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netcontrol_FairyTale_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030Cubie/BaseCommands.proto\022\nnetcontrol\"\375" +
      "\001\n\014BaseCommands\022+\n\004type\030\001 \002(\0162\035.netcontr" +
      "ol.BaseCommands.Type\022,\n\013deviceState\030\002 \001(" +
      "\0132\027.netcontrol.DeviceState\022,\n\013streamSoun" +
      "d\030\003 \001(\0132\027.netcontrol.StreamSound\022(\n\tfair" +
      "yTale\030\004 \001(\0132\025.netcontrol.FairyTale\":\n\004Ty" +
      "pe\022\020\n\014DEVICE_STATE\020\001\022\020\n\014STREAM_SOUND\020\002\022\016" +
      "\n\nFAIRY_TALE\020\003\"~\n\013DeviceState\022/\n\004type\030\001 " +
      "\002(\0162!.netcontrol.DeviceState.Direction\022\r" +
      "\n\005sound\030\002 \001(\002\022\r\n\005power\030\003 \001(\010\" \n\tDirectio",
      "n\022\010\n\004READ\020\001\022\t\n\005WRITE\020\002\"+\n\013StreamSound\022\014\n" +
      "\004port\030\001 \001(\005\022\016\n\006reload\030\002 \002(\010\".\n\tFairyTale" +
      "\022\014\n\004name\030\001 \002(\t\022\023\n\010position\030\002 \001(\005:\0010B\nB\010C" +
      "ommands"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netcontrol_BaseCommands_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netcontrol_BaseCommands_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_netcontrol_BaseCommands_descriptor,
        new java.lang.String[] { "Type", "DeviceState", "StreamSound", "FairyTale", });
    internal_static_netcontrol_DeviceState_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_netcontrol_DeviceState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_netcontrol_DeviceState_descriptor,
        new java.lang.String[] { "Type", "Sound", "Power", });
    internal_static_netcontrol_StreamSound_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_netcontrol_StreamSound_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_netcontrol_StreamSound_descriptor,
        new java.lang.String[] { "Port", "Reload", });
    internal_static_netcontrol_FairyTale_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_netcontrol_FairyTale_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_netcontrol_FairyTale_descriptor,
        new java.lang.String[] { "Name", "Position", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
